services:
  ventoy:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ventoy-wrapper:dev
    working_dir: /workspace
    volumes:
      - ..:/workspace
